# Generated by Django 2.0 on 2019-01-04 01:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaiGouDianShengChan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zdsj', models.DateField(default=django.utils.timezone.now, verbose_name='制定时间')),
                ('status', models.BooleanField(help_text='整个计划是否完成', verbose_name='状态')),
                ('dgd', models.ForeignKey(limit_choices_to={'jglb': 'DGD'}, on_delete=django.db.models.deletion.CASCADE, to='company.JiGou', verbose_name='代购点')),
            ],
            options={
                'verbose_name_plural': '代购点生产计划',
                'verbose_name': '代购点生产计划',
            },
        ),
        migrations.CreateModel(
            name='GongSiShengChan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scjhbh', models.CharField(max_length=50, unique=True, verbose_name='生产计划编号')),
                ('zdsj', models.DateField(default=django.utils.timezone.now, verbose_name='制定时间')),
                ('status', models.BooleanField(help_text='整个计划是否完成', verbose_name='状态')),
            ],
            options={
                'verbose_name_plural': '公司生产计划',
                'verbose_name': '公司生产计划',
            },
        ),
        migrations.CreateModel(
            name='NongHuShengChan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zdsj', models.DateField(default=django.utils.timezone.now, verbose_name='制定时间')),
                ('status', models.BooleanField(help_text='整个计划是否完成', verbose_name='状态')),
                ('nh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.NongHuXinXi', verbose_name='农户')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.DaiGouDianShengChan', verbose_name='父计划')),
            ],
            options={
                'verbose_name_plural': '农户生产计划',
                'verbose_name': '农户生产计划',
            },
        ),
        migrations.CreateModel(
            name='ShengChanJiDiShengChan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zdsj', models.DateField(default=django.utils.timezone.now, verbose_name='制定时间')),
                ('status', models.BooleanField(help_text='整个计划是否完成', verbose_name='状态')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.GongSiShengChan', verbose_name='父计划')),
                ('scjd', models.ForeignKey(limit_choices_to={'jglb': 'SCJD'}, on_delete=django.db.models.deletion.CASCADE, to='company.JiGou', verbose_name='生产基地')),
            ],
            options={
                'verbose_name_plural': '生产基地生产计划',
                'verbose_name': '生产基地生产计划',
            },
        ),
        migrations.CreateModel(
            name='ShuCaiShengChan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zzmj', models.IntegerField(verbose_name='种植面积')),
                ('dw', models.CharField(max_length=5, verbose_name='单位')),
                ('bzq', models.DateField(verbose_name='播种期')),
                ('scbh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.ChanPinXinXi', verbose_name='蔬菜编号')),
            ],
            options={
                'verbose_name_plural': '蔬菜生产计划',
                'verbose_name': '蔬菜生产计划',
            },
        ),
        migrations.AddField(
            model_name='shengchanjidishengchan',
            name='scscjh',
            field=models.ManyToManyField(blank=True, to='product.ShuCaiShengChan', verbose_name='蔬菜生产计划'),
        ),
        migrations.AddField(
            model_name='shengchanjidishengchan',
            name='zdr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Employee', to_field='name', verbose_name='制定人'),
        ),
        migrations.AddField(
            model_name='nonghushengchan',
            name='scscjh',
            field=models.ManyToManyField(blank=True, to='product.ShuCaiShengChan', verbose_name='蔬菜生产计划'),
        ),
        migrations.AddField(
            model_name='nonghushengchan',
            name='zdr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Employee', to_field='name', verbose_name='制定人'),
        ),
        migrations.AddField(
            model_name='gongsishengchan',
            name='scscjh',
            field=models.ManyToManyField(blank=True, to='product.ShuCaiShengChan', verbose_name='蔬菜生产计划'),
        ),
        migrations.AddField(
            model_name='gongsishengchan',
            name='zdr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Employee', to_field='name', verbose_name='制定人'),
        ),
        migrations.AddField(
            model_name='daigoudianshengchan',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ShengChanJiDiShengChan', verbose_name='父计划'),
        ),
        migrations.AddField(
            model_name='daigoudianshengchan',
            name='scscjh',
            field=models.ManyToManyField(blank=True, to='product.ShuCaiShengChan', verbose_name='蔬菜生产计划'),
        ),
        migrations.AddField(
            model_name='daigoudianshengchan',
            name='zdr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Employee', to_field='name', verbose_name='制定人'),
        ),
    ]
