# Generated by Django 2.0 on 2019-01-04 01:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChanPinChuKu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ckdh', models.CharField(max_length=50, unique=True, verbose_name='出库单号')),
                ('dj', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='单价')),
                ('sl', models.IntegerField(default=0, verbose_name='数量')),
                ('je', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20, null=True, verbose_name='金额')),
                ('czsj', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间')),
                ('pm', models.CharField(blank=True, editable=False, max_length=10, null=True, verbose_name='片名')),
                ('date', models.DateField(blank=True, editable=False, null=True, verbose_name='日期')),
            ],
            options={
                'verbose_name_plural': '产品出库',
                'verbose_name': '产品出库',
            },
        ),
        migrations.CreateModel(
            name='ChanPinKuCun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpkcbh', models.CharField(editable=False, max_length=50, verbose_name='产品库存编号')),
                ('cpmc', models.CharField(default='', editable=False, max_length=50, verbose_name='产品名称')),
                ('cpbh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.ChanPinXinXi', verbose_name='产品编号')),
                ('ssjg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.JiGou', verbose_name='所属机构')),
            ],
            options={
                'verbose_name_plural': '产品库存',
                'verbose_name': '产品库存',
            },
        ),
        migrations.CreateModel(
            name='ChanPinPanCun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl', models.IntegerField(default=0, verbose_name='数量')),
                ('pcsj', models.DateTimeField(default=django.utils.timezone.now, verbose_name='盘存时间')),
                ('date', models.DateField(blank=True, editable=False, null=True, verbose_name='日期')),
                ('cpkc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.ChanPinKuCun', verbose_name='产品库存')),
                ('jsr', models.ForeignKey(blank=True, help_text='默认为填表人', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pc_jsr', to='company.Employee', verbose_name='盘存经手人')),
            ],
            options={
                'verbose_name_plural': '产品盘存',
                'verbose_name': '产品盘存',
            },
        ),
        migrations.CreateModel(
            name='ChanPinRuKu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rkdh', models.CharField(max_length=50, unique=True, verbose_name='入库单号')),
                ('dj', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='单价')),
                ('sl', models.IntegerField(default=0, verbose_name='数量')),
                ('je', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20, null=True, verbose_name='金额')),
                ('czsj', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间')),
                ('pm', models.CharField(blank=True, editable=False, max_length=30, null=True, verbose_name='片名')),
                ('date', models.DateField(blank=True, editable=False, null=True, verbose_name='日期')),
                ('ckdh', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.ChanPinChuKu', verbose_name='对应出库单号')),
                ('cpkc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.ChanPinKuCun', verbose_name='产品库存表')),
                ('jsr', models.ForeignKey(blank=True, editable=False, help_text='默认为填表人', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rk_jsr', to='company.Employee', to_field='name', verbose_name='经手人')),
                ('jyr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rk_jyr', to='company.Employee', to_field='name', verbose_name='检验人')),
                ('nh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.NongHuXinXi', verbose_name='负责农户')),
            ],
            options={
                'verbose_name_plural': '产品入库',
                'verbose_name': '产品入库',
            },
        ),
        migrations.CreateModel(
            name='ChanPinXiaoShou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xsdh', models.CharField(max_length=10, unique=True, verbose_name='销售单号')),
                ('dj', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='单价')),
                ('sl', models.IntegerField(default=0, verbose_name='数量')),
                ('je', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20, null=True, verbose_name='金额')),
                ('xssj', models.DateTimeField(default=django.utils.timezone.now, verbose_name='销售时间')),
                ('date', models.DateField(blank=True, editable=False, null=True, verbose_name='日期')),
                ('cpkc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.ChanPinKuCun', verbose_name='产品库存')),
                ('gk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.GuKeXinXi', verbose_name='顾客')),
                ('jsr', models.ForeignKey(help_text='默认为填表人', on_delete=django.db.models.deletion.CASCADE, related_name='xs_jsr', to='company.Employee', to_field='name', verbose_name='销售经手人')),
            ],
            options={
                'verbose_name_plural': '产品销售',
                'verbose_name': '产品销售',
            },
        ),
        migrations.AddField(
            model_name='chanpinchuku',
            name='cpkc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.ChanPinKuCun', verbose_name='产品库存表'),
        ),
        migrations.AddField(
            model_name='chanpinchuku',
            name='jsr',
            field=models.ForeignKey(blank=True, editable=False, help_text='默认为填表人', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ck_jsr', to='company.Employee', to_field='name', verbose_name='经手人'),
        ),
        migrations.AddField(
            model_name='chanpinchuku',
            name='jyr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ck_jyr', to='company.Employee', to_field='name', verbose_name='检验人'),
        ),
        migrations.AddField(
            model_name='chanpinchuku',
            name='nh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.NongHuXinXi', verbose_name='负责农户'),
        ),
        migrations.AddField(
            model_name='chanpinchuku',
            name='rkdh',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.ChanPinRuKu', verbose_name='对应入库单号'),
        ),
    ]
