# Generated by Django 2.0 on 2019-01-04 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20190104_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chanpinxinxi',
            name='jgbh',
            field=models.ForeignKey(blank=True, limit_choices_to={'jglb': 'JD'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.JiGou', verbose_name='基地编号'),
        ),
        migrations.AlterField(
            model_name='nonghuxinxi',
            name='dgd',
            field=models.ForeignKey(limit_choices_to={'jglb': 'DG'}, on_delete=django.db.models.deletion.CASCADE, to='company.JiGou', verbose_name='所属代购点'),
        ),
    ]
